// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/discovered_word.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 6752048034514049591),
      name: 'DiscoveredWord',
      lastPropertyId: const IdUid(6, 540593637611515591),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3839526099041725299),
            name: 'entryNumber',
            type: 6,
            flags: 40,
            indexId: const IdUid(1, 4633317927544905904)),
        ModelProperty(
            id: const IdUid(2, 2948905778078834034),
            name: 'failedMeaningReviews',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3550581583680862779),
            name: 'failedReadingReviews',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4736474625265313524),
            name: 'successMeaningReviews',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 8487175969304409037),
            name: 'successReadingReviews',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 540593637611515591),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 6752048034514049591),
      lastIndexId: const IdUid(1, 4633317927544905904),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    DiscoveredWord: EntityDefinition<DiscoveredWord>(
        model: _entities[0],
        toOneRelations: (DiscoveredWord object) => [],
        toManyRelations: (DiscoveredWord object) => {},
        getId: (DiscoveredWord object) => object.entryNumber,
        setId: (DiscoveredWord object, int id) {
          object.entryNumber = id;
        },
        objectToFB: (DiscoveredWord object, fb.Builder fbb) {
          fbb.startTable(7);
          fbb.addInt64(0, object.entryNumber);
          fbb.addInt64(1, object.failedMeaningReviews);
          fbb.addInt64(2, object.failedReadingReviews);
          fbb.addInt64(3, object.successMeaningReviews);
          fbb.addInt64(4, object.successReadingReviews);
          fbb.addInt64(5, object.id);
          fbb.finish(fbb.endTable());
          return object.entryNumber;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final entryNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final successMeaningReviewsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final failedMeaningReviewsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final successReadingReviewsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final failedReadingReviewsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final object = DiscoveredWord(
              entryNumber: entryNumberParam,
              successMeaningReviews: successMeaningReviewsParam,
              failedMeaningReviews: failedMeaningReviewsParam,
              successReadingReviews: successReadingReviewsParam,
              failedReadingReviews: failedReadingReviewsParam,
              id: idParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [DiscoveredWord] entity fields to define ObjectBox queries.
class DiscoveredWord_ {
  /// see [DiscoveredWord.entryNumber]
  static final entryNumber =
      QueryIntegerProperty<DiscoveredWord>(_entities[0].properties[0]);

  /// see [DiscoveredWord.failedMeaningReviews]
  static final failedMeaningReviews =
      QueryIntegerProperty<DiscoveredWord>(_entities[0].properties[1]);

  /// see [DiscoveredWord.failedReadingReviews]
  static final failedReadingReviews =
      QueryIntegerProperty<DiscoveredWord>(_entities[0].properties[2]);

  /// see [DiscoveredWord.successMeaningReviews]
  static final successMeaningReviews =
      QueryIntegerProperty<DiscoveredWord>(_entities[0].properties[3]);

  /// see [DiscoveredWord.successReadingReviews]
  static final successReadingReviews =
      QueryIntegerProperty<DiscoveredWord>(_entities[0].properties[4]);

  /// see [DiscoveredWord.id]
  static final id =
      QueryIntegerProperty<DiscoveredWord>(_entities[0].properties[5]);
}
